site_name: General Bikeshare Feed Specification
site_url: https://gbfs.org
repo_url: https://github.com/nabsa/gbfs

theme:
  logo_light_mode: assets/org-white.svg
  logo_dark_mode: assets/library-white.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
  name: material
  custom_dir: overrides
  favicon: assets/org.svg
  font:
    text: SF Pro
    code: SF Mono
  features:
     - navigation.tabs
     - navigation.indexes
     - navigation.top
     - toc.integrate
  custom_dir: theme_overrides
extra_css:
  - assets/stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MobilityData
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/mobilitydata
    - icon: fontawesome/brands/slack
      link: https://bit.ly/mobilitydata-slack

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences

plugins:
  - search
  - mkdocs-simple-hooks:
      hooks:
        on_config: "hooks.on_config:deploy_hooks"

nav:
- Home: index.md
- Reference: reference.md
- Major Change Proposals: major-change-proposals.md
- Resources: resources.md
- FAQ: faq.md
- About: about.md