site_name: General Bikeshare Feed Specification
site_url: https://gbfs.org
repo_url: https://github.com/nabsa/gbfs

theme:
  logo_light_mode: https://raw.githubusercontent.com/squidfunk/mkdocs-material/master/material/.icons/material/library.svg
  logo_dark_mode: assets/library-white.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  name: material
  # favicon: assets/org.svg
  font:
    text: Helvetica
    code: Source Code Pro
  features:
     - navigation.tabs
     - toc.integrate
     - navigation.indexes
     - navigation.top
  custom_dir: theme_overrides
extra_css:
  - assets/stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MobilityData
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/mobilitydata
    - icon: fontawesome/brands/slack
      link: https://bit.ly/mobilitydata-slack

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences

plugins:
  - search
  - mkdocs-simple-hooks:
      hooks:
        on_config: "hooks.on_config:deploy_hooks"

nav:
- Home: index.md
- Reference: reference.md
- Major Change Proposals: major-change-proposals.md
- Tools & Services: 
  - tools-services/index.md
  - Policy Guides: tools-services/policy-guides.md
  - Articles: tools-services/articles.md
  - Data: tools-services/data.md
  - Software for Creating APIs: tools-services/software-for-creating-apis.md
  - Apps: tools-services/apps.md
  - Visualizations: tools-services/visualizations.md
  - GBFS: tools-services/gbfs.md
  - Other Multimodal Data Formats: tools-services/multimodal.md
- FAQ: 
  - faq/index.md
  - Open Data Standards: faq/open-data-standards.md
  - Uses of GBFS: faq/uses-of-gbfs.md
  - systems.csv: faq/systems.md
  - Shared Mobility: faq/shared-mobility.md
  - Governance and Change Process: faq/governance.md
  - GitHub: faq/github.md
  - Working with GBFS: faq/working-with-gbfs.md
  - Glossary: faq/glossary.md
  - MobilityData: faq/mobilitydata.md
- About: about.md